packages:
  - apps/webui
  - sdks/ts
  - sdks/ts/packages/*
  - .agents/skills/playwright-skill

allowBuilds:
  "@kie/act-js": true
  "@parcel/watcher": true
  "@j178/prek": true
  esbuild: true

overrides:
  # for tsdown peer dependency
  typescript: 6.0.2
