/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PlaygroundRouteRouteImport } from "./routes/_playground/route"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as LoginIndexRouteImport } from "./routes/login/index"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedGroupsIndexRouteImport } from "./routes/_authenticated/groups/index"
import { Route as AuthenticatedEntriesIndexRouteImport } from "./routes/_authenticated/entries/index"
import { Route as PlaygroundPlaygroundSessionRouteImport } from "./routes/_playground/playground/session"
import { Route as PlaygroundPlaygroundBasicAuthRouteImport } from "./routes/_playground/playground/basic-auth"
import { Route as AuthenticatedGroupsNewRouteImport } from "./routes/_authenticated/groups/new"
import { Route as AuthenticatedEntriesNewRouteImport } from "./routes/_authenticated/entries/new"
import { Route as AuthTokenSetFrontendModePopupCallbackRouteImport } from "./routes/auth/token-set/frontend-mode/popup-callback"
import { Route as AuthTokenSetFrontendModeCallbackRouteImport } from "./routes/auth/token-set/frontend-mode/callback"
import { Route as PlaygroundPlaygroundTokenSetFrontendModeRouteImport } from "./routes/_playground/playground/token-set/frontend-mode"
import { Route as PlaygroundPlaygroundTokenSetBackendModeRouteImport } from "./routes/_playground/playground/token-set/backend-mode"
import { Route as AuthenticatedGroupsGroupIdEditRouteImport } from "./routes/_authenticated/groups/$groupId/edit"
import { Route as AuthenticatedEntriesEntryIdEditRouteImport } from "./routes/_authenticated/entries/$entryId/edit"

const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: "/_playground",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: "/groups/",
    path: "/groups/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesIndexRoute =
  AuthenticatedEntriesIndexRouteImport.update({
    id: "/entries/",
    path: "/entries/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PlaygroundPlaygroundSessionRoute =
  PlaygroundPlaygroundSessionRouteImport.update({
    id: "/playground/session",
    path: "/playground/session",
    getParentRoute: () => PlaygroundRouteRoute,
  } as any)
const PlaygroundPlaygroundBasicAuthRoute =
  PlaygroundPlaygroundBasicAuthRouteImport.update({
    id: "/playground/basic-auth",
    path: "/playground/basic-auth",
    getParentRoute: () => PlaygroundRouteRoute,
  } as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: "/groups/new",
  path: "/groups/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntriesNewRoute = AuthenticatedEntriesNewRouteImport.update({
  id: "/entries/new",
  path: "/entries/new",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthTokenSetFrontendModePopupCallbackRoute =
  AuthTokenSetFrontendModePopupCallbackRouteImport.update({
    id: "/auth/token-set/frontend-mode/popup-callback",
    path: "/auth/token-set/frontend-mode/popup-callback",
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthTokenSetFrontendModeCallbackRoute =
  AuthTokenSetFrontendModeCallbackRouteImport.update({
    id: "/auth/token-set/frontend-mode/callback",
    path: "/auth/token-set/frontend-mode/callback",
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaygroundPlaygroundTokenSetFrontendModeRoute =
  PlaygroundPlaygroundTokenSetFrontendModeRouteImport.update({
    id: "/playground/token-set/frontend-mode",
    path: "/playground/token-set/frontend-mode",
    getParentRoute: () => PlaygroundRouteRoute,
  } as any)
const PlaygroundPlaygroundTokenSetBackendModeRoute =
  PlaygroundPlaygroundTokenSetBackendModeRouteImport.update({
    id: "/playground/token-set/backend-mode",
    path: "/playground/token-set/backend-mode",
    getParentRoute: () => PlaygroundRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdEditRoute =
  AuthenticatedGroupsGroupIdEditRouteImport.update({
    id: "/groups/$groupId/edit",
    path: "/groups/$groupId/edit",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesEntryIdEditRoute =
  AuthenticatedEntriesEntryIdEditRouteImport.update({
    id: "/entries/$entryId/edit",
    path: "/entries/$entryId/edit",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/login/": typeof LoginIndexRoute
  "/entries/new": typeof AuthenticatedEntriesNewRoute
  "/groups/new": typeof AuthenticatedGroupsNewRoute
  "/playground/basic-auth": typeof PlaygroundPlaygroundBasicAuthRoute
  "/playground/session": typeof PlaygroundPlaygroundSessionRoute
  "/entries/": typeof AuthenticatedEntriesIndexRoute
  "/groups/": typeof AuthenticatedGroupsIndexRoute
  "/entries/$entryId/edit": typeof AuthenticatedEntriesEntryIdEditRoute
  "/groups/$groupId/edit": typeof AuthenticatedGroupsGroupIdEditRoute
  "/playground/token-set/backend-mode": typeof PlaygroundPlaygroundTokenSetBackendModeRoute
  "/playground/token-set/frontend-mode": typeof PlaygroundPlaygroundTokenSetFrontendModeRoute
  "/auth/token-set/frontend-mode/callback": typeof AuthTokenSetFrontendModeCallbackRoute
  "/auth/token-set/frontend-mode/popup-callback": typeof AuthTokenSetFrontendModePopupCallbackRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute
  "/login": typeof LoginIndexRoute
  "/entries/new": typeof AuthenticatedEntriesNewRoute
  "/groups/new": typeof AuthenticatedGroupsNewRoute
  "/playground/basic-auth": typeof PlaygroundPlaygroundBasicAuthRoute
  "/playground/session": typeof PlaygroundPlaygroundSessionRoute
  "/entries": typeof AuthenticatedEntriesIndexRoute
  "/groups": typeof AuthenticatedGroupsIndexRoute
  "/entries/$entryId/edit": typeof AuthenticatedEntriesEntryIdEditRoute
  "/groups/$groupId/edit": typeof AuthenticatedGroupsGroupIdEditRoute
  "/playground/token-set/backend-mode": typeof PlaygroundPlaygroundTokenSetBackendModeRoute
  "/playground/token-set/frontend-mode": typeof PlaygroundPlaygroundTokenSetFrontendModeRoute
  "/auth/token-set/frontend-mode/callback": typeof AuthTokenSetFrontendModeCallbackRoute
  "/auth/token-set/frontend-mode/popup-callback": typeof AuthTokenSetFrontendModePopupCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/_playground": typeof PlaygroundRouteRouteWithChildren
  "/_authenticated/": typeof AuthenticatedIndexRoute
  "/login/": typeof LoginIndexRoute
  "/_authenticated/entries/new": typeof AuthenticatedEntriesNewRoute
  "/_authenticated/groups/new": typeof AuthenticatedGroupsNewRoute
  "/_playground/playground/basic-auth": typeof PlaygroundPlaygroundBasicAuthRoute
  "/_playground/playground/session": typeof PlaygroundPlaygroundSessionRoute
  "/_authenticated/entries/": typeof AuthenticatedEntriesIndexRoute
  "/_authenticated/groups/": typeof AuthenticatedGroupsIndexRoute
  "/_authenticated/entries/$entryId/edit": typeof AuthenticatedEntriesEntryIdEditRoute
  "/_authenticated/groups/$groupId/edit": typeof AuthenticatedGroupsGroupIdEditRoute
  "/_playground/playground/token-set/backend-mode": typeof PlaygroundPlaygroundTokenSetBackendModeRoute
  "/_playground/playground/token-set/frontend-mode": typeof PlaygroundPlaygroundTokenSetFrontendModeRoute
  "/auth/token-set/frontend-mode/callback": typeof AuthTokenSetFrontendModeCallbackRoute
  "/auth/token-set/frontend-mode/popup-callback": typeof AuthTokenSetFrontendModePopupCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login/"
    | "/entries/new"
    | "/groups/new"
    | "/playground/basic-auth"
    | "/playground/session"
    | "/entries/"
    | "/groups/"
    | "/entries/$entryId/edit"
    | "/groups/$groupId/edit"
    | "/playground/token-set/backend-mode"
    | "/playground/token-set/frontend-mode"
    | "/auth/token-set/frontend-mode/callback"
    | "/auth/token-set/frontend-mode/popup-callback"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/entries/new"
    | "/groups/new"
    | "/playground/basic-auth"
    | "/playground/session"
    | "/entries"
    | "/groups"
    | "/entries/$entryId/edit"
    | "/groups/$groupId/edit"
    | "/playground/token-set/backend-mode"
    | "/playground/token-set/frontend-mode"
    | "/auth/token-set/frontend-mode/callback"
    | "/auth/token-set/frontend-mode/popup-callback"
  id:
    | "__root__"
    | "/_authenticated"
    | "/_playground"
    | "/_authenticated/"
    | "/login/"
    | "/_authenticated/entries/new"
    | "/_authenticated/groups/new"
    | "/_playground/playground/basic-auth"
    | "/_playground/playground/session"
    | "/_authenticated/entries/"
    | "/_authenticated/groups/"
    | "/_authenticated/entries/$entryId/edit"
    | "/_authenticated/groups/$groupId/edit"
    | "/_playground/playground/token-set/backend-mode"
    | "/_playground/playground/token-set/frontend-mode"
    | "/auth/token-set/frontend-mode/callback"
    | "/auth/token-set/frontend-mode/popup-callback"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlaygroundRouteRoute: typeof PlaygroundRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  AuthTokenSetFrontendModeCallbackRoute: typeof AuthTokenSetFrontendModeCallbackRoute
  AuthTokenSetFrontendModePopupCallbackRoute: typeof AuthTokenSetFrontendModePopupCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_playground": {
      id: "/_playground"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login/": {
      id: "/login/"
      path: "/login"
      fullPath: "/login/"
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/groups/": {
      id: "/_authenticated/groups/"
      path: "/groups"
      fullPath: "/groups/"
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/entries/": {
      id: "/_authenticated/entries/"
      path: "/entries"
      fullPath: "/entries/"
      preLoaderRoute: typeof AuthenticatedEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_playground/playground/session": {
      id: "/_playground/playground/session"
      path: "/playground/session"
      fullPath: "/playground/session"
      preLoaderRoute: typeof PlaygroundPlaygroundSessionRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    "/_playground/playground/basic-auth": {
      id: "/_playground/playground/basic-auth"
      path: "/playground/basic-auth"
      fullPath: "/playground/basic-auth"
      preLoaderRoute: typeof PlaygroundPlaygroundBasicAuthRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    "/_authenticated/groups/new": {
      id: "/_authenticated/groups/new"
      path: "/groups/new"
      fullPath: "/groups/new"
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/entries/new": {
      id: "/_authenticated/entries/new"
      path: "/entries/new"
      fullPath: "/entries/new"
      preLoaderRoute: typeof AuthenticatedEntriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/auth/token-set/frontend-mode/popup-callback": {
      id: "/auth/token-set/frontend-mode/popup-callback"
      path: "/auth/token-set/frontend-mode/popup-callback"
      fullPath: "/auth/token-set/frontend-mode/popup-callback"
      preLoaderRoute: typeof AuthTokenSetFrontendModePopupCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/token-set/frontend-mode/callback": {
      id: "/auth/token-set/frontend-mode/callback"
      path: "/auth/token-set/frontend-mode/callback"
      fullPath: "/auth/token-set/frontend-mode/callback"
      preLoaderRoute: typeof AuthTokenSetFrontendModeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_playground/playground/token-set/frontend-mode": {
      id: "/_playground/playground/token-set/frontend-mode"
      path: "/playground/token-set/frontend-mode"
      fullPath: "/playground/token-set/frontend-mode"
      preLoaderRoute: typeof PlaygroundPlaygroundTokenSetFrontendModeRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    "/_playground/playground/token-set/backend-mode": {
      id: "/_playground/playground/token-set/backend-mode"
      path: "/playground/token-set/backend-mode"
      fullPath: "/playground/token-set/backend-mode"
      preLoaderRoute: typeof PlaygroundPlaygroundTokenSetBackendModeRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    "/_authenticated/groups/$groupId/edit": {
      id: "/_authenticated/groups/$groupId/edit"
      path: "/groups/$groupId/edit"
      fullPath: "/groups/$groupId/edit"
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/entries/$entryId/edit": {
      id: "/_authenticated/entries/$entryId/edit"
      path: "/entries/$entryId/edit"
      fullPath: "/entries/$entryId/edit"
      preLoaderRoute: typeof AuthenticatedEntriesEntryIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEntriesNewRoute: typeof AuthenticatedEntriesNewRoute
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedEntriesIndexRoute: typeof AuthenticatedEntriesIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedEntriesEntryIdEditRoute: typeof AuthenticatedEntriesEntryIdEditRoute
  AuthenticatedGroupsGroupIdEditRoute: typeof AuthenticatedGroupsGroupIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEntriesNewRoute: AuthenticatedEntriesNewRoute,
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedEntriesIndexRoute: AuthenticatedEntriesIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedEntriesEntryIdEditRoute: AuthenticatedEntriesEntryIdEditRoute,
  AuthenticatedGroupsGroupIdEditRoute: AuthenticatedGroupsGroupIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlaygroundRouteRouteChildren {
  PlaygroundPlaygroundBasicAuthRoute: typeof PlaygroundPlaygroundBasicAuthRoute
  PlaygroundPlaygroundSessionRoute: typeof PlaygroundPlaygroundSessionRoute
  PlaygroundPlaygroundTokenSetBackendModeRoute: typeof PlaygroundPlaygroundTokenSetBackendModeRoute
  PlaygroundPlaygroundTokenSetFrontendModeRoute: typeof PlaygroundPlaygroundTokenSetFrontendModeRoute
}

const PlaygroundRouteRouteChildren: PlaygroundRouteRouteChildren = {
  PlaygroundPlaygroundBasicAuthRoute: PlaygroundPlaygroundBasicAuthRoute,
  PlaygroundPlaygroundSessionRoute: PlaygroundPlaygroundSessionRoute,
  PlaygroundPlaygroundTokenSetBackendModeRoute:
    PlaygroundPlaygroundTokenSetBackendModeRoute,
  PlaygroundPlaygroundTokenSetFrontendModeRoute:
    PlaygroundPlaygroundTokenSetFrontendModeRoute,
}

const PlaygroundRouteRouteWithChildren = PlaygroundRouteRoute._addFileChildren(
  PlaygroundRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlaygroundRouteRoute: PlaygroundRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  AuthTokenSetFrontendModeCallbackRoute: AuthTokenSetFrontendModeCallbackRoute,
  AuthTokenSetFrontendModePopupCallbackRoute:
    AuthTokenSetFrontendModePopupCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
