// @securitydept/client — Foundation public API
// --- Auth Coordination ---
export {
	type AuthenticatedCheck,
	type AuthRequirement,
	BaseRequirementPlanner,
	type CheckAuthenticated,
	defaultSelectCandidate,
	isRouteBehaviourContextExtra,
	isRouteStateSnapshotTrait,
	MergeRequirementPlanner,
	type OnUnauthenticated,
	PipelineOutcome,
	type PipelineRunResult,
	type PipelineStepResult,
	PlanStatus,
	type RequirementBehaviour,
	type RequirementBehaviourContext,
	type RequirementBehaviourWithRouteContext,
	type RequirementCandidateGenerator,
	type RequirementCandidateSelectionContext,
	type RequirementPlan,
	RequirementPlannerError,
	RequirementPlannerHost,
	type RequirementPlannerHostOptions,
	type RequirementResolution,
	RequirementsComposition,
	ResolutionStatus,
	type RouteBehaviourContextExtra,
	RouteCompositionRequirementPlanner,
	type RouteRequirementsDeclaration,
	type RouteStateSnapshotTrait,
	type RouteTreeSegment,
	resolveEffectiveRequirements,
	type SelectCandidate,
	StaticAttrsAuthRequirement,
	type StaticAttrsAuthRequirementInput,
	StaticRequirementPlanner,
	type UnauthenticatedAction,
} from "./auth-coordination";
// --- Cancellation ---
export {
	type CancelableHandle,
	type CancellationTokenSourceTrait,
	type CancellationTokenTrait,
	createCancellationTokenSource,
	createLinkedCancellationToken,
	isCancellationTokenTrait,
} from "./cancellation";
// --- Compat ---
export {
	type AsyncDisposableTrait,
	type DisposableTrait,
	type InteropObservableTrait,
	isInteropObservableTrait,
	type ObserverTrait,
	promisesToRacedAsyncGenerator,
	type SubscribableTrait,
	type SubscriptionTrait,
	SYMBOL_ASYNC_DISPOSE,
	SYMBOL_DISPOSE,
	SYMBOL_OBSERVABLE,
} from "./compat";
// --- Environment ---
export {
	type CreateFoundationEnvironmentOptions,
	createFoundationEnvironment,
	type EnvironmentValidators,
	FOUNDATION_ENVIRONMENT_TOKEN,
	type FoundationEnvironment,
	type ServiceWorkerEnvironment,
} from "./environment";
// --- Errors ---
export {
	ClientError,
	type ClientErrorAttributes,
	ClientErrorKind,
	type ClientErrorRecovery,
	ClientErrorSource,
	describeError,
	type ErrorAttributes,
	type ErrorPresentation,
	type ErrorPresentationActionDescriptor,
	type ErrorPresentationDescriptor,
	ErrorPresentationTone,
	type NativeErrorAttributes,
	type ReadErrorPresentationDescriptorOptions,
	readErrorPresentationDescriptor,
	type UnknownErrorAttributes,
	UserRecovery,
} from "./errors";
// --- Events ---
export {
	abortSignalToEventStream,
	createEmptyEventStream,
	createEventReplaySubject,
	createEventStream,
	createEventSubject,
	createNeverEventStream,
	type EventObserverTrait,
	type EventOperatorFunction,
	type EventSource,
	EventSourceKind,
	type EventStreamTrait,
	type EventSubjectTrait,
	type EventSubscriptionTrait,
	type RuntimeEventEnvelope,
	type ToEventStreamInput,
	toEventStream,
} from "./events";
// --- Identity ---
export {
	type IdentityPrincipal,
	IdentityPrincipalSchema,
	IdentityPrincipalWireSchema,
	type ProjectIdentityPrincipalOptions,
	parseIdentityPrincipal,
	parseIdentityPrincipalWire,
	projectIdentityPrincipal,
} from "./identity";
// --- Injection ---
export {
	createProviderIfTokenMissing,
	createSecuritydeptDestroyRef,
	getSecuritydeptProviderToken,
	INJECTOR_TOKEN,
	inject,
	notMissingProvider,
	runInInjectionContext,
	SecurityDeptOptional,
	type SecuritydeptAbstractType,
	type SecuritydeptClassProvider,
	type SecuritydeptDependencyDescriptor,
	type SecuritydeptDependencyToken,
	SecuritydeptDestroyRef,
	type SecuritydeptExistingProvider,
	type SecuritydeptFactoryProvider,
	SecuritydeptInjectionToken,
	type SecuritydeptInjectOptions,
	SecuritydeptInjector,
	type SecuritydeptInjectorTrait,
	type SecuritydeptProvider,
	type SecuritydeptTypeProvider,
	type SecuritydeptValueProvider,
	tryInjectInInjectionContext,
	type WithTraitDeps,
} from "./injection";
// --- Page ---
export {
	PAGE_LIFECYCLE_TRAIT_TOKEN,
	type PageLifecycleTrait,
} from "./page";
// --- Popup ---
export {
	type CreatePopupClientSessionOptions,
	type CreatePopupServerSessionOptions,
	POPUP_TRAIT_TOKEN,
	type PopupAttachFailure,
	PopupAttachFailureReason,
	type PopupAttachResult,
	type PopupAttachSuccess,
	PopupClientWindowHandle,
	type PopupClientWindowHandleTrait,
	PopupErrorCode,
	type PopupMessageChannelTrait,
	type PopupOpenOptions,
	PopupServerWindowHandle,
	type PopupServerWindowHandleTrait,
	type PopupTrait,
	type PopupWindowHandleTrait,
} from "./popup";
// --- Protocol ---
export {
	type AppendOrReplaceCompatFragmentOptions,
	type AppendOrReplaceCompatFragmentResult,
	appendOrReplaceCompatFragment,
	type CompatFragment,
	isCompatFragmentBlock,
	parseCompatFragment,
	SECURITYDEPT_COMPAT_FRAGMENT_VERSION,
	type TakeCompatFragmentResult,
	takeCompatFragment,
	type UpdateUriFragmentHash,
} from "./protocol/compat-fragment";
export {
	type CreateJsonRpcClientOptions,
	type CreateJsonRpcServerAndClientOptions,
	type CreateJsonRpcServerOptions,
	createJsonRpcClient,
	createJsonRpcServer,
	createJsonRpcServerAndClient,
	type JsonRpcClientTrait,
	type JsonRpcErrorPayload,
	type JsonRpcErrorResponseMessage,
	type JsonRpcId,
	type JsonRpcMessage,
	type JsonRpcNotificationEvent,
	type JsonRpcNotificationMessage,
	type JsonRpcRequestEvent,
	type JsonRpcRequestMessage,
	type JsonRpcRequestOptions,
	type JsonRpcServerAndClientTrait,
	type JsonRpcServerTrait,
	type JsonRpcSuccessResponseMessage,
} from "./protocol/json-rpc";
export {
	type DecodeJwtPayloadOptions,
	decodeJwtPayload,
	type JwtAudienceClaim,
	type JwtClaimsSet,
} from "./protocol/jwt";
// --- Router ---
export {
	BaseURIStringSchema,
	ROUTER_TRAIT_TOKEN,
	RouterNavigationIntent,
	RouterNavigationMode,
	type RouterNavigationRequest,
	type RouterTrait,
	readSecuritydeptRouteMetadata,
	SECURITYDEPT_ROUTE_METADATA_KEY,
	type SecuritydeptRouteMetadata,
	takeCompatFragmentFromRouter,
	UriReferenceStringSchema,
	writeSecuritydeptRouteMetadata,
} from "./router";
// --- Scheduling ---
export {
	createDefaultTimeConfig,
	IDLE_CALLBACK_TRAIT_TOKEN,
	type IdleCallbackTrait,
	parseDurationToMs,
	TIME_TRAIT_TOKEN,
	type TimestampProviderTrait,
	type TimeTrait,
} from "./scheduling";
// --- Signals ---
export {
	type ComputedReplaySignalTrait,
	type ComputedSignalTrait,
	createAndThenComputedReplaySignal,
	createComputed,
	createComputedReplaySignal,
	createReplaySignal,
	createSignal,
	isReplaySignalTrait,
	type ReadableReplaySignalTrait,
	type ReadableSignalTrait,
	type ReplaySignalSlot,
	type ReplaySignalWhenValueOptions,
	readonlyReplaySignal,
	readonlySignal,
	type WritableReplaySignalTrait,
	type WritableSignalTrait,
} from "./signals";
// --- Span ---
export {
	createRootSpan,
	type OperationSpanTrait,
	SPAN_TRAIT_TOKEN,
	type SpanCreateOptions,
	type SpanTrait,
} from "./span";
// --- Std ---
export {
	abortSignalToCancellationToken,
	type BaseTransportForStdFetchCreateOptions,
	cancellationTokenToAbortSignal,
	createBaseTransportForStdFetch,
	createTimeForStd,
	FetchTransportRedirectKind,
	normalizeAbortError,
	type TimeForStdCreateOptions,
} from "./std";
// --- Storage ---
export {
	type Codec,
	createEphemeralFlowStore,
	createInMemoryRecordStore,
	createJsonCodec,
	createKeyedEphemeralFlowStore,
	type EphemeralFlowStore,
	type KeyedEphemeralFlowStore,
	PERSISTENT_STORAGE_TRAIT_TOKEN,
	type PersistentAuthStore,
	type RecoverableStateStore,
	SESSION_STORAGE_TRAIT_TOKEN,
	type StorageTrait,
	type StoredEnvelope,
} from "./storage";
// --- Structs ---
export {
	createOnceAsyncLockCallable,
	type OnceAsyncLock,
	type OnceAsyncLockCallable,
	type OnceAsyncLockError,
	type OnceAsyncLockInit,
	type OnceAsyncLockRunning,
	OnceAsyncLockState,
	type OnceAsyncLockSuccess,
	type UriFragmentPart,
	UriParseError,
	UriReferenceString,
	type UriReferenceStringLike,
	type UriRelativeParts,
	UriRelativeString,
	UriString,
} from "./struct";
// --- Tracing ---
export {
	createConsoleTracingSubscriber,
	createTraceTimelineStore,
	createTracing,
	type DefineInstrumentMethodDecoratorContext,
	type DefineInstrumentMethodDecoratorFactory,
	defineInstrumentMethodDecorator,
	type InstrumentMethodResolvedOptions,
	type InstrumentMethodThisContext,
	type InstrumentMethodThisResolver,
	OperationTraceEventType,
	type RunOperationEnvironment,
	type RunOperationOptions,
	type RunOperationOptionsBase,
	runOperation,
	TRACING_TRAIT_TOKEN,
	type TraceTimelineEntry,
	type TraceTimelineStore,
	type TracingCreateOptions,
	type TracingEvent,
	TracingLevel,
	type TracingSubscriberTrait,
	type TracingTrait,
} from "./tracing";
// --- Transport ---
export {
	type BaseTransportTrait,
	type HttpRequest,
	type HttpResponse,
	isLoopbackHttpUrl,
	TRANSPORT_TRAIT_TOKEN,
} from "./transport";
// --- Validation ---
export {
	formatValidationFailure,
	type TraitInputValidator,
	throwValidationClientError,
	type ValidateTraitInputOptions,
	type ValidationFailure,
	type ValidationResult,
	type ValidationSuccess,
	validateTraitInput,
	validateWithSchema,
	validateWithSchemaSync,
	type WithTraitInputValidator,
} from "./validation";
