// @securitydept/client — Foundation public API
// --- Auth Coordination ---
export {
	type AuthenticatedCheck,
	type AuthRequirement,
	BaseRequirementPlanner,
	type CheckAuthenticated,
	defaultSelectCandidate,
	type InjectRequirementPlannerHostOptions,
	injectRequirementPlannerHost,
	isRouteBehaviourContextExtra,
	isRouteStateSnapshotTrait,
	MergeRequirementPlanner,
	type OnUnauthenticated,
	PipelineOutcome,
	type PipelineRunResult,
	type PipelineStepResult,
	PlanStatus,
	type ProvideRequirementPlannerHostOptions,
	provideRequirementPlannerHost,
	REQUIREMENT_PLANNER_HOST,
	type RequirementBehaviour,
	type RequirementBehaviourContext,
	type RequirementBehaviourWithRouteContext,
	type RequirementCandidateGenerator,
	type RequirementCandidateSelectionContext,
	type RequirementPlan,
	RequirementPlannerError,
	RequirementPlannerHost,
	type RequirementPlannerHostBehaviour,
	type RequirementPlannerHostOptions,
	type RequirementResolution,
	RequirementsComposition,
	ResolutionStatus,
	type RouteBehaviourContextExtra,
	RouteCompositionRequirementPlanner,
	type RouteRequirementsDeclaration,
	type RouteStateSnapshotTrait,
	type RouteTreeSegment,
	resolveEffectiveRequirements,
	type SelectCandidate,
	StaticAttrsAuthRequirement,
	type StaticAttrsAuthRequirementInput,
	StaticRequirementPlanner,
	type UnauthenticatedAction,
} from "./auth-coordination";
// --- Cancellation ---
export {
	type CancelableHandle,
	type CancellationTokenOptions,
	type CancellationTokenSourceTrait,
	type CancellationTokenTrait,
	createCancellationTokenSource,
	createLinkedCancellationToken,
	isCancellationTokenTrait,
} from "./cancellation";
// --- Compat ---
export {
	type AsyncDisposableTrait,
	Base64CompatErrorCode,
	createDisposableStack,
	type DisposableStackTrait,
	type DisposableTrait,
	decodeBase64ToUint8Array,
	encodeUint8ArrayToBase64,
	type InteropObservableTrait,
	injectDisposableStackFrom,
	isInteropObservableTrait,
	type ObserverTrait,
	promisesToRacedAsyncGenerator,
	SimpleDisposableStack,
	StdDisposableStack,
	type SubscribableTrait,
	type SubscriptionTrait,
	SYMBOL_ASYNC_DISPOSE,
	SYMBOL_DISPOSABLE_STACK,
	SYMBOL_DISPOSE,
	SYMBOL_OBSERVABLE,
	type WithInteropObservableTraitCompat,
	withDisposableStack,
} from "./compat";
// --- Environment ---
export {
	type CreateFoundationEnvironmentOptions,
	createFoundationEnvironment,
	ENVIRONMENT_TOKEN,
	type EnvironmentValidators,
	type FoundationEnvironment,
	type ServiceWorkerEnvironment,
} from "./environment";
// --- Errors ---
export {
	ClientError,
	type ClientErrorFromHttpResponseOptions,
	type ClientErrorFromUnknownOptions,
	ClientErrorKind,
	ClientErrorSource,
	describeError,
	type ErrorCodePresentationDescriptor,
	type ErrorPresentation,
	type ErrorPresentationActionDescriptor,
	type ErrorPresentationDescriptor,
	ErrorPresentationTone,
	type ErrorSummary,
	type ReadErrorPresentationDescriptorOptions,
	readErrorPresentationDescriptor,
	UserRecovery,
} from "./errors";
// --- Events ---
export {
	abortSignalToEventStream,
	createEmptyEventStream,
	createEventReplaySubject,
	createEventStream,
	createEventSubject,
	createNeverEventStream,
	type EventObserverTrait,
	type EventOperatorFunction,
	type EventSource,
	EventSourceKind,
	type EventStreamTrait,
	type EventSubjectTrait,
	type EventSubscriptionTrait,
	type RuntimeEventEnvelope,
	type ToEventStreamInput,
	toEventStream,
} from "./events";
// --- Identity ---
export {
	type IdentityPrincipal,
	IdentityPrincipalSchema,
	IdentityPrincipalWireSchema,
	type ProjectIdentityPrincipalOptions,
	parseIdentityPrincipal,
	parseIdentityPrincipalWire,
	projectIdentityPrincipal,
} from "./identity";
// --- Injection ---
export {
	createProviderIfTokenMissing,
	createSecuritydeptDestroyRef,
	getSecuritydeptProviderToken,
	INJECTOR_TOKEN,
	inject,
	notMissingProvider,
	runInInjectionContext,
	SecurityDeptOptional,
	type SecuritydeptAbstractType,
	type SecuritydeptClassProvider,
	type SecuritydeptDependencyDescriptor,
	type SecuritydeptDependencyToken,
	SecuritydeptDestroyRef,
	type SecuritydeptExistingProvider,
	type SecuritydeptFactoryProvider,
	SecuritydeptInjectionToken,
	type SecuritydeptInjectOptions,
	SecuritydeptInjector,
	type SecuritydeptInjectorTrait,
	type SecuritydeptProvider,
	type SecuritydeptTypeProvider,
	type SecuritydeptValueProvider,
	tryInjectInInjectionContext,
	type WithTraitDeps,
} from "./injection";
// --- Page ---
export {
	PAGE_LIFECYCLE_TRAIT_TOKEN,
	type PageLifecycleTrait,
} from "./page";
// --- Popup ---
export {
	type CreatePopupClientSessionOptions,
	type CreatePopupServerSessionOptions,
	POPUP_TRAIT_TOKEN,
	type PopupAttachFailure,
	PopupAttachFailureReason,
	type PopupAttachResult,
	type PopupAttachSuccess,
	PopupClientWindowHandle,
	type PopupClientWindowHandleTrait,
	PopupErrorCode,
	type PopupMessageChannelTrait,
	type PopupOpenOptions,
	PopupServerWindowHandle,
	type PopupServerWindowHandleTrait,
	type PopupTrait,
	type PopupWindowHandleTrait,
	readPopupErrorPresentationDescriptor,
} from "./popup";
// --- Protocol ---
export {
	type AppendOrReplaceCompatFragmentOptions,
	type AppendOrReplaceCompatFragmentResult,
	appendOrReplaceCompatFragment,
	type CompatFragment,
	type CompatFragmentParameters,
	isCompatFragmentBlock,
	parseCompatFragment,
	SECURITYDEPT_COMPAT_FRAGMENT_VERSION,
	type TakeCompatFragmentOptions,
	type TakeCompatFragmentResult,
	takeCompatFragment,
	type UpdateUriFragmentHash,
} from "./protocol/compat-fragment";
export {
	type CreateJsonRpcClientOptions,
	type CreateJsonRpcServerAndClientOptions,
	type CreateJsonRpcServerOptions,
	createJsonRpcClient,
	createJsonRpcServer,
	createJsonRpcServerAndClient,
	type JsonRpcClientTrait,
	type JsonRpcErrorPayload,
	type JsonRpcErrorResponseMessage,
	type JsonRpcId,
	type JsonRpcMessage,
	type JsonRpcNotificationEvent,
	type JsonRpcNotificationMessage,
	type JsonRpcRequestEvent,
	type JsonRpcRequestMessage,
	type JsonRpcRequestOptions,
	type JsonRpcServerAndClientTrait,
	type JsonRpcServerTrait,
	type JsonRpcSuccessResponseMessage,
} from "./protocol/json-rpc";
export {
	type DecodeJwtPayloadOptions,
	decodeJwtPayload,
	type JwtAudienceClaim,
	type JwtClaimsSet,
	JwtDecodeError,
	JwtDecodeErrorCode,
} from "./protocol/jwt";
// --- Router ---
export {
	ROUTER_TRAIT_TOKEN,
	RouterNavigationIntent,
	RouterNavigationMode,
	type RouterNavigationRequest,
	type RouterTrait,
	readSecuritydeptRouteMetadata,
	SECURITYDEPT_ROUTE_METADATA_KEY,
	type SecuritydeptRouteMetadata,
	type TakeCompatFragmentFromRouterOptions,
	takeCompatFragmentFromRouter,
	writeSecuritydeptRouteMetadata,
} from "./router";
// --- Scheduling ---
export {
	IDLE_CALLBACK_TRAIT_TOKEN,
	type IdleCallbackTrait,
	parseDurationToMs,
	TIME_TRAIT_TOKEN,
	type TimestampProviderTrait,
	type TimeTrait,
} from "./scheduling";
// --- Signals ---
export {
	type ComputedSignalTrait,
	type CreateResourceOptions,
	createComputed,
	createResource,
	createSignal,
	flattenResourceSnapshot,
	mapResource,
	type ReadableSignalTrait,
	ResourceError,
	ResourceErrorCode,
	type ResourceErrorSnapshot,
	type ResourceIdleSnapshot,
	type ResourceLoadingErrorSnapshot,
	type ResourceLoadingSnapshot,
	type ResourceReloadingSnapshot,
	type ResourceResolvedSnapshot,
	type ResourceSnapshot,
	type ResourceSnapshotUpdate,
	ResourceSnapshotUpdateKind,
	ResourceStatus,
	type ResourceStreamContext,
	type ResourceTrait,
	type ResourceValueUnavailableErrorOptions,
	type ResourceWhenValueOptions,
	readonlySignal,
	reduceResourceSnapshot,
	resourceFromSnapshots,
	type WritableSignalTrait,
} from "./signals";
// --- Span ---
export {
	createRootSpan,
	type OperationSpanTrait,
	SPAN_TRAIT_TOKEN,
	type SpanCreateOptions,
	type SpanTrait,
} from "./span";
// --- Std ---
export {
	type AuthorizationInterceptedFetchPredicate,
	type AuthorizationSignal,
	abortSignalToCancellationToken,
	type BaseTransportForStdFetchCreateOptions,
	type CreateAuthorizationInterceptedFetchOptions,
	cancellationTokenToAbortSignal,
	createAuthorizationInterceptedFetch,
	createBaseTransportForStdFetch,
	createTimeForStd,
	FetchTransportRedirectKind,
	normalizeAbortError,
	type TimeForStdCreateOptions,
} from "./std";
// --- Storage ---
export {
	type Codec,
	createEphemeralFlowStore,
	createInMemoryRecordStore,
	createJsonCodec,
	createKeyedEphemeralFlowStore,
	type EphemeralFlowStore,
	type KeyedEphemeralFlowStore,
	PERSISTENT_STORAGE_TRAIT_TOKEN,
	type PersistentAuthStore,
	REALM_STORAGE_TRAIT_TOKEN,
	type RecoverableStateStore,
	SESSION_STORAGE_TRAIT_TOKEN,
	type StorageChangeEvent,
	StorageChangeEventOrigin,
	type StorageTrait,
	type StoredEnvelope,
	type SyncStorageTrait,
} from "./storage";
// --- Structs ---
export {
	createOnceAsyncLockCallable,
	type OnceAsyncLock,
	type OnceAsyncLockCallable,
	type OnceAsyncLockError,
	type OnceAsyncLockInit,
	type OnceAsyncLockRunning,
	OnceAsyncLockState,
	type OnceAsyncLockSuccess,
	type UriFragmentPart,
	UriParseError,
	UriReferenceString,
	type UriReferenceStringInput,
	type UriReferenceStringLike,
	type UriRelativeParts,
	UriRelativeString,
	type UriSearchParamsInit,
	UriString,
} from "./struct";
// --- Tracing ---
export {
	createConsoleTracingSubscriber,
	createTraceTimelineStore,
	createTracing,
	type DefineInstrumentMethodDecoratorContext,
	type DefineInstrumentMethodDecoratorFactory,
	defineInstrumentMethodDecorator,
	type InstrumentMethodResolvedOptions,
	type InstrumentMethodThisContext,
	type InstrumentMethodThisResolver,
	OperationSpan,
	OperationTraceEventType,
	type RunOperationEnvironment,
	type RunOperationOptions,
	type RunOperationOptionsBase,
	runOperation,
	TRACING_TRAIT_TOKEN,
	type TraceTimelineEntry,
	type TraceTimelineStore,
	type TracingCreateOptions,
	type TracingEvent,
	TracingLevel,
	type TracingSubscriberTrait,
	type TracingTrait,
} from "./tracing";
// --- Transport ---
export {
	type BaseTransportTrait,
	type HttpRequest,
	type HttpResponse,
	type HttpResponseJsonBody,
	isLoopbackHttpUrl,
	TRANSPORT_TRAIT_TOKEN,
	TransportErrorCode,
} from "./transport";
// --- Validation ---
export {
	BaseURIStringSchema,
	formatValidationFailure,
	type TraitInputValidator,
	throwValidationClientError,
	UriReferenceStringSchema,
	UriRelativeStringSchema,
	UriStringSchema,
	type ValidateTraitInputOptions,
	type ValidationFailure,
	type ValidationResult,
	type ValidationSuccess,
	validateTraitInput,
	validateWithSchema,
	validateWithSchemaSync,
	type WithTraitInputValidator,
} from "./validation";
